runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /css
  static_dir: statics/css
- url: /js
  static_dir: statics/js
- url: /img
  static_dir: statics/img
- url: /
  static_files: statics/index.html
  upload: statics/index.html
- url: /data
  static_dir: statics/data
- url: /api/.*
  script: _go_app
- url: /.*
  script: _go_app

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic